spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:/home/ohierro/projects/04_training/tecnara_course/java03/myDatabase"
    driver-class-name: org.h2.Driver
server:
  port: 8085


