spring:
  datasource:
    url: "jdbc:h2:/home/ohierro/projects/04_training/tecnara_course/java04/core/myDatabase"
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8085
---
spring:
  profiles: integration
  datasource:
    url: "jdbc:h2:/home/ohierro/projects/04_training/tecnara_course/java04/core/ci-test"
    driver-class-name: org.h2.Driver
